/**
 * An autogenerated component that renders the CDOT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
import PropTypes from "prop-types";
import * as React from "react";

class Cdot extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g fill="none" fillRule="evenodd">
                    <path fill="none" d="M0 0h48v48H0z" />
                    <g transform="translate(12 12)">
                        <path fill="none" d="M0 0h24v24H0z" />
                        <circle fill={this.props.color} cx="12" cy="12" r="3" />
                    </g>
                </g>
            </svg>
        );
    }
}

export default Cdot;
