# npm package registry for pnpm install
registry.npmjs.org
# Cypress binary download during pnpm exec cypress install
download.cypress.io
# Cypress binary CDN for pnpm exec cypress install
cdn.cypress.io
