# Domains needed for Trusted Publishing (OIDC)

# signing certificates are stored here
fulcio.sigstore.dev
# signing certificates are stored here
rekor.sigstore.dev

# needed to fetch timestamp for signing
timestamp.sigstore.dev
