coverage:
    precision: 2
    round: down
    range: "70...100"

comment:
    layout: "diff, reach, files, footer"
    behavior: default
    require_changes: false
    require_base: false
    require_head: true

# https://docs.codecov.com/docs/ignoring-paths
ignore:
    - "utils/*.js"
    - "packages/**/dist/index.ts"
    - "packages/**/types.ts"
    - "packages/**/*-types.ts"
    - "packages/**/*.cypress.tsx"
    - "packages/**/*.cypress.ts"
