packages:
    - config/build
    - dev
    - packages/*
    - vendor/*
catalog:
    react: ^18.2.0
    react-dom: ^18.2.0
    aphrodite: ^1.2.5
    classnames: 1.1.4
    jquery: ^2.1.1
    prop-types: 15.6.1
    tiny-invariant: ^1.3.1
    underscore: ^1.4.4
    vite: 5.1.0
    "@khanacademy/mathjax-renderer": ^3.0.0
    "@khanacademy/wonder-blocks-accordion": 3.1.14
    "@khanacademy/wonder-blocks-banner": 4.1.16
    "@khanacademy/wonder-blocks-button": 10.0.1
    "@khanacademy/wonder-blocks-clickable": 7.1.2
    "@khanacademy/wonder-blocks-core": 12.3.0
    "@khanacademy/wonder-blocks-data": 14.1.4
    "@khanacademy/wonder-blocks-dropdown": 10.1.1
    "@khanacademy/wonder-blocks-form": 7.1.14
    "@khanacademy/wonder-blocks-icon-button": 10.0.0
    "@khanacademy/wonder-blocks-icon": 5.1.4
    "@khanacademy/wonder-blocks-labeled-field": 3.0.9
    "@khanacademy/wonder-blocks-layout": 3.1.13
    "@khanacademy/wonder-blocks-link": 9.1.2
    "@khanacademy/wonder-blocks-pill": 3.1.14
    "@khanacademy/wonder-blocks-popover": 6.1.2
    "@khanacademy/wonder-blocks-progress-spinner": 3.1.13
    "@khanacademy/wonder-blocks-search-field": 5.1.16
    "@khanacademy/wonder-blocks-switch": 3.2.6
    "@khanacademy/wonder-blocks-timing": 7.0.2
    "@khanacademy/wonder-blocks-tokens": 10.2.0
    "@khanacademy/wonder-blocks-toolbar": 5.1.13
    "@khanacademy/wonder-blocks-tooltip": 4.1.16
    "@khanacademy/wonder-blocks-typography": 3.2.3
    "@khanacademy/wonder-stuff-core": 1.5.4
    "@phosphor-icons/core": ^2.0.2
    "@popperjs/core": ^2.10.2
