packages:
    - 'config/build'
    - 'dev'
    - 'packages/*'
    - 'vendor/*'

catalog:
    react: ^18.2.0
    react-dom: ^18.2.0
    aphrodite: ^1.2.5
    classnames: 1.1.4
    jquery: ^2.1.1
    prop-types: 15.6.1
    underscore: ^1.4.4
    "@khanacademy/mathjax-renderer": ^2.1.1
    "@khanacademy/wonder-blocks-accordion": 3.1.1
    "@khanacademy/wonder-blocks-banner": 4.1.1
    "@khanacademy/wonder-blocks-button": 7.1.1
    "@khanacademy/wonder-blocks-clickable": 6.1.1
    "@khanacademy/wonder-blocks-core": 12.1.1
    "@khanacademy/wonder-blocks-data": 14.1.1
    "@khanacademy/wonder-blocks-dropdown": 9.1.1
    "@khanacademy/wonder-blocks-form": 7.1.1
    "@khanacademy/wonder-blocks-icon-button": 6.1.1
    "@khanacademy/wonder-blocks-icon": 5.1.1
    "@khanacademy/wonder-blocks-layout": 3.1.1
    "@khanacademy/wonder-blocks-link": 7.1.1
    "@khanacademy/wonder-blocks-pill": 3.1.1
    "@khanacademy/wonder-blocks-popover": 5.1.1
    "@khanacademy/wonder-blocks-progress-spinner": 3.1.1
    "@khanacademy/wonder-blocks-search-field": 4.0.6
    "@khanacademy/wonder-blocks-switch": 3.1.1
    "@khanacademy/wonder-blocks-timing": 7.0.1
    "@khanacademy/wonder-blocks-tokens": 4.2.1
    "@khanacademy/wonder-blocks-toolbar": 5.0.5
    "@khanacademy/wonder-blocks-tooltip": 4.0.3
    "@khanacademy/wonder-blocks-typography": 3.1.1
    "@khanacademy/wonder-stuff-core": 1.5.4
    "@phosphor-icons/core": ^2.0.2
    "@popperjs/core": ^2.10.2
