// WARNING: Do not change or delete this file! If you do, Perseus might become
// unable to parse the current data format, which will break clients.
// If you need to add more regression tests, add a new file to this directory.
export default {
    question: {
        content: "crwdns3120949:0crwdne3120949:0",
        widgets: {
            "input-number 1": {
                type: "input-number",
                static: false,
                graded: true,
                alignment: "",
                id: null,
                key: null,
                version: null,
                options: {
                    answerType: "number",
                    value: 18,
                    maxError: 0.1,
                    simplify: "required",
                    inexact: false,
                    rightAlign: false,
                    answers: [],
                    labelText: "",
                    size: "normal",
                    coefficient: false,
                    textAlign: "",
                },
            },
        },
        replace: null,
        metadata: null,
        images: {},
    },
    hints: [
        {
            content: "crwdns2937155:0crwdne2937155:0",
            widgets: {},
            replace: null,
            metadata: null,
            images: {},
        },
        {
            content: "crwdns2937153:0crwdne2937153:0",
            widgets: {},
            replace: null,
            metadata: null,
            images: {},
        },
        {
            content: "crwdns2688103:0{1.20}crwdne2688103:0",
            widgets: {},
            replace: null,
            metadata: null,
            images: {},
        },
        {
            content: "crwdns2689139:0{1.2}crwdne2689139:0",
            widgets: {},
            replace: null,
            metadata: null,
            images: {},
        },
    ],
    answerArea: {
        type: "multiple",
        static: false,
        graded: false,
        alignment: "",
        id: null,
        key: null,
        version: null,
        zTable: false,
        chi2Table: false,
        tTable: false,
        calculator: false,
        calculatorVariant: null,
        periodicTable: false,
        periodicTableWithKey: false,
        financialCalculatorMonthlyPayment: false,
        financialCalculatorTotalAmount: false,
        financialCalculatorTimeToPayOff: false,
        options: {
            content: "",
            widgets: {},
            replace: null,
            metadata: null,
            images: {},
        },
    },
    _multi: null,
    itemDataVersion: {},
    answer: null,
};
