// flow-typed signature: 02e095fc2135e742ae3a993ce37b6294
// flow-typed version: <<STUB>>/ancesdir_v1.1.0/flow_v0.176.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ancesdir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ancesdir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ancesdir/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ancesdir/dist/index' {
  declare module.exports: $Exports<'ancesdir/dist'>;
}
declare module 'ancesdir/dist/index.js' {
  declare module.exports: $Exports<'ancesdir/dist'>;
}
