name: 'Filter files'
description: 'Filter the list of changed files'
inputs:
  changed-files:
    description: 'jsonified list of changed files from setup'
    required: true
  files:
    description: 'comma-separated list of files to check for'
    required: false
  extensions:
    description: 'comma-separated list of extensions to check for'
    required: false
outputs:
  filtered:
    description: 'The jsonified list of files that match'
    value: ${{ steps.result.outputs.result }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: result
      with:
        script: |
          const extensionsRaw = "${{ inputs.extensions }}";
          const exactFilesRaw = "${{ inputs.files }}";
          const inputFiles = JSON.parse(`${{ inputs.changed-files }}`);
          const extensions = extensionsRaw.trim() ? extensionsRaw.split(',') : [];
          const exactFiles = exactFilesRaw.trim() ? exactFilesRaw.split(',') : [];

          const result = inputFiles.filter(name => {
            return extensions.some(ext => name.endsWith(ext)) || (
              exactFiles.includes(name)
            )
          })
          console.log(`Filtered Files: ${JSON.stringify(result)}`)
          return result;
        result-encoding: json
