import _ from "underscore";

export type Entry = {
    value: string;
    added?: boolean;
    removed?: boolean;
};

// Split a word-wise diff generated by jsdiff into multiple lines, for the
// purpose of breaking up the diffs into lines, so that modified lines can be
// faintly highlighted
const splitDiff = function (diffEntries: Entry[]): Entry[][] {
    const lines: Entry[][] = [];
    let currentLine: Entry[] = [];
    _.each(diffEntries, (entry) => {
        const values = entry.value.split("\n");
        _.each(values, (value, i) => {
            const isNewline = i > 0;
            if (isNewline) {
                lines.push(currentLine);
                currentLine = [];
            }
            const newEntry: Entry = _.extend({}, entry, {
                value: value,
            });
            currentLine.push(newEntry);
        });
    });

    if (currentLine.length > 0) {
        lines.push(currentLine);
    }

    return lines;
};

export default splitDiff;
