name: "Branch Compare"
description: "Compare artifacts between PR branch and base branch"

inputs:
    build-command:
        description: "The command that generates the artifact to compare"
        required: true
    path-to-artifact:
        description: >-
            The path to the artifact to compare - should be the same for both
            the current branch and base branch. Write artifacts from the
            `build-command` to `${{ runner.temp }}`/... to pass files in a temp
            directory.
        required: true
    label-name:
        description: "The name of the label to add or remove based on the diff result"
        required: true

outputs:
    pr-artifact-path:
        description: "Path to the artifact generated for the PR branch"
    base-artifact-path:
        description: "Path to the artifact generated for the base branch"
    diff-exit-code:
        description: "Exit code of the diff command (0 if no changes, non-zero otherwise)"
    diff-content:
        description: "The diff content between the PR and base branch artifacts"
    comment-title-term:
        description: >-
            The term to include in the title of comments made by this action.
    comment-title-emoji:
        description: >-
            The emoji to prefix comment titles with. Makes these comments
            easily identifiable and differentiated.

runs:
    using: "composite"
    steps:
        - name: Check out latest commit
          uses: actions/checkout@v4

        - name: Install & cache node_modules
          uses: ./.github/actions/shared-node-cache
          with:
              node-version: ${{ matrix.node-version }}

        - name: Build for current PR
          shell: bash
          run: ${{ inputs.build-command }}

        - name: Capture output artifact from build-command for current PR
          shell: bash
          run: |
              PR_ARTIFACT_DIR="${{ runner.temp }}/branch-compare/pr"
              mkdir -p "$PR_ARTIFACT_DIR"
              cp ${{ inputs.path-to-artifact }} "$PR_ARTIFACT_DIR/"
              echo "pr-artifact-path=$PR_ARTIFACT_DIR" >> $GITHUB_OUTPUT

        - name: Check out base branch
          uses: actions/checkout@v4
          with:
              # This checks out the base branch of the PR (the branch the PR
              # is targeting)
              ref: ${{ github.event.pull_request.base.ref }}

        - name: Re-install node_modules for base branch
          shell: bash
          run: |
              pnpm clean
              pnpm install

        - name: Build for base
          shell: bash
          run: ${{ inputs.build-command }}

        - name: Capture output artifact from build-command for base branch
          shell: bash
          run: |
              BASE_ARTIFACT_DIR="${{ runner.temp }}/branch-compare/base"
              mkdir -p "$BASE_ARTIFACT_DIR"
              cp ${{ inputs.path-to-artifact }} "$BASE_ARTIFACT_DIR/"
              echo "base-artifact-path=$BASE_ARTIFACT_DIR" >> $GITHUB_OUTPUT

        - name: Compare Artifacts
          id: compare-artifacts
          shell: bash
          run: |
              set +e
              DELIM=$(uuidgen)
              echo "DIFF_CONTENT<<$DELIM" >> "$GITHUB_OUTPUT"
              diff --unified "$BASE_ARTIFACT_DIR/$(basename ${{ inputs.path-to-artifact }})" \
                        "$PR_ARTIFACT_DIR/$(basename ${{ inputs.path-to-artifact }})" >> "$GITHUB_OUTPUT"
              DIFF_EXIT_CODE=$?
              echo "$DELIM" >> "$GITHUB_OUTPUT"
              echo "diff-exit-code=$DIFF_EXIT_CODE" >> "$GITHUB_OUTPUT"

        - name: Add or Remove Label Based on Diff
          if: always()
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          shell: bash
          run: |
              PR_NUMBER="${{ github.event.pull_request.number }}"
              if [ "${{ steps.compare-artifacts.outputs.diff-exit-code }}" -ne 0 ]; then
                  gh pr edit "$PR_NUMBER" --add-label "${{ inputs.label-name }}"
              else
                  gh pr edit "$PR_NUMBER" --remove-label "${{ inputs.label-name }}" || true
              fi

        - name: Find comment
          uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
          id: find-comment
          with:
              issue-number: ${{ github.event.pull_request.number }}
              comment-author: "github-actions[bot]"
              body-includes: "Comment ID: ${{ inputs.comment-title-term }}"

        - name: Create or update comment - success
          if: steps.compare-artifacts.outputs.diff_exit_code == '0'
          uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
          with:
              issue-number: ${{ github.event.pull_request.number }}
              comment-id: ${{ steps.find-comment.outputs.comment-id}}
              edit-mode: replace
              body: |
                  # ${{ inputs.comment-title-emoji }} ${{ inputs.comment-title-term }}: No Changes ✅

                  <!---
                  Comment ID: ${{ inputs.comment-title-term }}
                  -->

        - name: Create or update comment - failure
          if: steps.compare-artifacts.outputs.diff_exit_code != '0'
          uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
          with:
              issue-number: ${{ github.event.pull_request.number }}
              comment-id: ${{ steps.find-comment.outputs.comment-id}}
              edit-mode: replace
              body: |
                  # ${{ inputs.comment-title-emoji }} ${{ inputs.comment-title-term }}: Changes Detected ⚠️

                  This PR contains changes to the Perseus '${{ inputs.comment-title-term }}'.

                  ```diff
                  ${{ steps.check_for_item_splitting_change.outputs.ITEM_SPLITTING_DIFF }}
                  ```

                  <!---
                  Comment ID: ${{ inputs.comment-title-term }}
                  -->
