import categorizerWidgetLogic from "./categorizer";
import csProgramWidgetLogic from "./cs-program";
import definitionWidgetLogic from "./definition";
import dropdownWidgetLogic from "./dropdown";
import explanationWidgetLogic from "./explanation";
import expressionWidgetLogic from "./expression";
import gradedGroupWidgetLogic from "./graded-group";
import gradedGroupSetWidgetLogic from "./graded-group-set";
import groupWidgetLogic from "./group";
import iframeWidgetLogic from "./iframe";
import imageWidgetLogic from "./image";
import inputNumberWidgetLogic from "./input-number";
import interactionWidgetLogic from "./interaction";
import interactiveGraphWidgetLogic from "./interactive-graph";
import labelImageWidgetLogic from "./label-image";
import matcherWidgetLogic from "./matcher";
import matrixWidgetLogic from "./matrix";
import measurerWidgetLogic from "./measurer";
import numberLineWidgetLogic from "./number-line";
import numericInputWidgetLogic from "./numeric-input";
import ordererWidgetLogic from "./orderer";
import passageWidgetLogic from "./passage";
import passageRefWidgetLogic from "./passage-ref";
import passageRefTargetWidgetLogic from "./passage-ref-target";
import phetSimulationWidgetLogic from "./phet-simulation";
import plotterWidgetLogic from "./plotter";
import pythonProgramWidgetLogic from "./python-program";
import radioWidgetLogic from "./radio";
import sorterWidgetLogic from "./sorter";
import tableWidgetLogic from "./table";
import videoWidgetLogic from "./video";

import type {WidgetLogic} from "./logic-export.types";

const widgets = {};

function registerWidget(type: string, logic: WidgetLogic) {
    widgets[type] = logic;
}

registerWidget("categorizer", categorizerWidgetLogic);
registerWidget("cs-program", csProgramWidgetLogic);
registerWidget("definition", definitionWidgetLogic);
registerWidget("dropdown", dropdownWidgetLogic);
registerWidget("explanation", explanationWidgetLogic);
registerWidget("expression", expressionWidgetLogic);
registerWidget("graded-group", gradedGroupWidgetLogic);
registerWidget("graded-group-set", gradedGroupSetWidgetLogic);
registerWidget("group", groupWidgetLogic);
registerWidget("iframe", iframeWidgetLogic);
registerWidget("image", imageWidgetLogic);
registerWidget("input-number", inputNumberWidgetLogic);
registerWidget("interaction", interactionWidgetLogic);
registerWidget("interactive-graph", interactiveGraphWidgetLogic);
registerWidget("label-image", labelImageWidgetLogic);
registerWidget("matcher", matcherWidgetLogic);
registerWidget("matrix", matrixWidgetLogic);
registerWidget("measurer", measurerWidgetLogic);
registerWidget("number-line", numberLineWidgetLogic);
registerWidget("numeric-input", numericInputWidgetLogic);
registerWidget("orderer", ordererWidgetLogic);
registerWidget("passage", passageWidgetLogic);
registerWidget("passage-ref", passageRefWidgetLogic);
registerWidget("passage-ref-target", passageRefTargetWidgetLogic);
registerWidget("phet-simulation", phetSimulationWidgetLogic);
registerWidget("plotter", plotterWidgetLogic);
registerWidget("python-program", pythonProgramWidgetLogic);
registerWidget("radio", radioWidgetLogic);
registerWidget("sorter", sorterWidgetLogic);
registerWidget("table", tableWidgetLogic);
registerWidget("video", videoWidgetLogic);
