/**
 * An autogenerated component that renders the BACKSPACE iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Backspace = (): React.ReactNode => {
    return (
        <svg width="48" height="48" viewbox="0 0 48 48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path
                    fill="#888D93"
                    d="m13 24 6 6h14V18H19l-6 6Zm-1.414-1.414 6-6A2 2 0 0 1 19 16h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H19a2 2 0 0 1-1.414-.586l-6-6a2 2 0 0 1 0-2.828Z"
                />
                <path
                    stroke="#888D93"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="m23 21 6 6M29 21l-6 6"
                />
                <g transform="translate(-50 -50)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M50 50h48v48H50z" />
                        <path
                            fill="#888D93"
                            d="m63 74 6 6h14V68H69l-6 6Zm-1.414-1.414 6-6A2 2 0 0 1 69 66h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H69a2 2 0 0 1-1.414-.586l-6-6a2 2 0 0 1 0-2.828Z"
                        />
                        <path
                            stroke="#888D93"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="m73 71 6 6M79 71l-6 6"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Backspace;
