/**
 * An autogenerated component that renders the DISMISS iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require("react");

const Dismiss = () => {
    return (
        <svg width="48" height="48" viewBox="0 0 48 48">
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path
                    d="M18 21l6 6 6-6"
                    strokeLinecap="round"
                    strokeWidth="2"
                    stroke="#71B307"
                    strokeLinejoin="round"
                />
            </g>
        </svg>
    );
};

module.exports = Dismiss;
