/**
 * An autogenerated component that renders the EXP_2 iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Exp_2 = (props: {color: string}): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path
                    fill={props.color}
                    d="M14 21c0-.552.456-1 1.002-1h9.996A1 1 0 0 1 26 21v14c0 .552-.456 1-1.002 1h-9.996A1 1 0 0 1 14 35V21Zm2 1h8v12h-8V22ZM33.67 23v-1.5h-2.44c1.66-1.16 2.39-2.03 2.39-3.05 0-1.34-1.13-2.22-2.7-2.22-.93 0-1.99.33-2.7 1.11l.95 1.14c.48-.45 1.04-.73 1.78-.73.49 0 .92.24.92.7 0 .66-.54 1.12-3.43 3.21V23h5.23Z"
                />
                <g transform="translate(-366 -654)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M366 654h48v48h-48z" />
                        <path
                            fill="#3B3E40"
                            d="M380 675c0-.552.456-1 1.002-1h9.996a1 1 0 0 1 1.002 1v14c0 .552-.456 1-1.002 1h-9.996a1 1 0 0 1-1.002-1v-14Zm2 1h8v12h-8v-12ZM399.67 677v-1.5h-2.44c1.66-1.16 2.39-2.03 2.39-3.05 0-1.34-1.13-2.22-2.7-2.22-.93 0-1.99.33-2.7 1.11l.95 1.14c.48-.45 1.04-.73 1.78-.73.49 0 .92.24.92.7 0 .66-.54 1.12-3.43 3.21V677h5.23Z"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Exp_2;
