/**
 * An autogenerated component that renders the FRAC_INCLUSIVE iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Frac_inclusive = (props: {color: string}): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <g transform="translate(12 12)">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path
                        fill={props.color}
                        d="M8 16.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997H8.997c-.55 0-.997-.453-.997-.997v-6.006ZM10 18h4v4h-4v-4Z"
                    />
                    <rect
                        width="20"
                        height="2"
                        x="2"
                        y="11"
                        fill="#3B3E40"
                        rx="1"
                    />
                    <path
                        fill="#3B3E40"
                        d="M8 .997C8 .447 8.453 0 8.997 0h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997H8.997C8.447 8 8 7.547 8 7.003V.997ZM10 2h4v4h-4V2Z"
                    />
                </g>
                <g transform="translate(-118 -450)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M118 450h48v48h-48z" />
                        <g transform="translate(130 462)">
                            <path fill="none" d="M0 0h24v24H0z" />
                            <path
                                fill="#3B3E40"
                                d="M8 16.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997H8.997c-.55 0-.997-.453-.997-.997v-6.006ZM10 18h4v4h-4v-4Z"
                            />
                            <rect
                                width="20"
                                height="2"
                                x="2"
                                y="11"
                                fill="#3B3E40"
                                rx="1"
                            />
                            <path
                                fill="#3B3E40"
                                d="M8 .997C8 .447 8.453 0 8.997 0h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997H8.997C8.447 8 8 7.547 8 7.003V.997ZM10 2h4v4h-4V2Z"
                            />
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Frac_inclusive;
