/**
 * An autogenerated component that renders the JUMP_OUT_EXPONENT iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Jump_out_exponent = (): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path fill="none" d="M12 12h24v24H12z" />
                <path
                    stroke="#78C008"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M35 19v16M23 19l8 8M31 23v4h-4"
                />
                <path
                    fill="#888D93"
                    d="M12 12.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997h-6.006c-.55 0-.997-.453-.997-.997v-6.006ZM14 14h4v4h-4v-4Z"
                />
                <g transform="translate(-118 -216)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M118 216h48v48h-48z" />
                        <path fill="none" d="M130 228h24v24h-24z" />
                        <path
                            stroke="#78C008"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M153 235v16M141 235l8 8M149 239v4h-4"
                        />
                        <path
                            fill="#888D93"
                            d="M130 228.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997h-6.006c-.55 0-.997-.453-.997-.997v-6.006Zm2 1.003h4v4h-4v-4Z"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Jump_out_exponent;
