/**
 * An autogenerated component that renders the JUMP_OUT_PARENTHESES iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Jump_out_parentheses = (): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path fill="none" d="M12 12h24v24H12z" />
                <path
                    stroke="#888D93"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M24 18c3 3 3 9 0 12M18 18c-3 3-3 9 0 12"
                />
                <path
                    stroke="#78C008"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="m32 27 3-3-3-3M22 24h12"
                />
                <g transform="translate(-118 -148)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M118 148h48v48h-48z" />
                        <path fill="none" d="M130 160h24v24h-24z" />
                        <path
                            stroke="#888D93"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M142 166c3 3 3 9 0 12M136 166c-3 3-3 9 0 12"
                        />
                        <path
                            stroke="#78C008"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="m150 175 3-3-3-3M140 172h12"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Jump_out_parentheses;
