/**
 * An autogenerated component that renders the JUMP_OUT_BASE iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Jump_out_base = (): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path fill="none" d="M12 12h24v24H12z" />
                <path
                    fill="#888D93"
                    d="M12 28.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997h-6.006c-.55 0-.997-.453-.997-.997v-6.006ZM14 30h4v4h-4v-4Z"
                />
                <path
                    stroke="#78C008"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M35 13v16M23 29l8-8M27 21h4v4"
                />
                <g transform="translate(-50 -216)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M50 216h48v48H50z" />
                        <path fill="none" d="M62 228h24v24H62z" />
                        <path
                            fill="#888D93"
                            d="M62 244.997c0-.55.453-.997.997-.997h6.006c.55 0 .997.453.997.997v6.006c0 .55-.453.997-.997.997h-6.006c-.55 0-.997-.453-.997-.997v-6.006ZM64 246h4v4h-4v-4Z"
                        />
                        <path
                            stroke="#78C008"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M85 229v16M73 245l8-8M77 237h4v4"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Jump_out_base;
