/**
 * An autogenerated component that renders the PERCENT iconograpy in SVG.
 *
 * Generated with: https://gist.github.com/crm416/3c7abc88e520eaed72347af240b32590.
 */
const React = require("react");
const PropTypes = require("prop-types");

class Percent extends React.Component {
    static propTypes = {
        color: PropTypes.string.isRequired,
    };

    render() {
        return (
            <svg width="48" height="48" viewBox="0 0 48 48">
                <g fill="none" fillRule="evenodd">
                    <path fill="none" d="M0 0h48v48H0z" />
                    <g transform="translate(12 12)">
                        <path fill="none" d="M0 0h24v24H0z" />
                        <path
                            d="M16 4L8 20"
                            stroke={this.props.color}
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                        />
                        <circle
                            stroke={this.props.color}
                            strokeWidth="2"
                            cx="7"
                            cy="7"
                            r="3"
                        />
                        <circle
                            stroke={this.props.color}
                            strokeWidth="2"
                            cx="17"
                            cy="17"
                            r="3"
                        />
                    </g>
                </g>
            </svg>
        );
    }
}

module.exports = Percent;
