/**
 * An autogenerated component that renders the PLUS iconograpy in SVG.
 *
 * Generated with: /Users/jeremy/khan/perseus/packages/math-input/tools/svg-to-react/convert.ts
 */
import * as React from "react";

const Plus = (props: {color: string}): React.ReactNode => {
    return (
        <svg width="48" height="48">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path
                    stroke={props.color}
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M19 24h10M24 29V19"
                />
                <g transform="translate(-50 -654)">
                    <mask id="b" fill="#fff">
                        <use xlinkhref="#a" />
                    </mask>
                    <use xlink:href="#a" fill="#FAFAFA" />
                    <g mask="url(#b)">
                        <path fill="none" d="M50 654h48v48H50z" />
                        <path
                            stroke="#3B3E40"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="2"
                            d="M69 678h10M74 683v-10"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Plus;
