import _ from "underscore";

// Split a word-wise diff generated by jsdiff into multiple lines, for the
// purpose of breaking up the diffs into lines, so that modified lines can be
// faintly highlighted

const splitDiff = function (diffEntries: any): any {
    const lines = [];
    let currentLine: Array<any> = [];
    _.each(diffEntries, (entry) => {
        const values = entry.value.split("\n");
        _.each(values, (value, i) => {
            const isNewline = i > 0;
            if (isNewline) {
                // @ts-expect-error - TS2345 - Argument of type 'any[]' is not assignable to parameter of type 'never'.
                lines.push(currentLine);
                currentLine = [];
            }
            const newEntry = _.extend({}, entry, {value: value});
            currentLine.push(newEntry);
        });
    });

    // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
    if (currentLine.length) {
        // @ts-expect-error - TS2345 - Argument of type 'any[]' is not assignable to parameter of type 'never'.
        lines.push(currentLine);
    }
    return lines;
};

export default splitDiff;
