name: 'Deploy Storybook to GitHub Pages'
description: 'Build and deploy Storybook to GitHub pages'
branding:
  icon: upload-cloud
  color: red
outputs:
  page_url:
    description: "The URL of the page"
    value: ${{ steps.deploy.outputs.page_url }}

runs:
  using: 'composite'

  steps:
    - name: Build Storybook
      shell: bash
      run: yarn build-storybook

    - name: Ensure .nojekyll file
      shell: bash
      run: install -d storybook-static/.nojekyll

    - name: Upload Storybook artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: storybook-static

    - id: deploy # So we can ref output variables
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}
