const MISSING_PERCENT_ERROR = "MISSING_PERCENT_ERROR";
const NEEDS_TO_BE_SIMPLIFIED_ERROR = "NEEDS_TO_BE_SIMPLIFIED_ERROR";
const APPROXIMATED_PI_ERROR = "APPROXIMATED_PI_ERROR";
const EXTRA_SYMBOLS_ERROR = "EXTRA_SYMBOLS_ERROR";
const WRONG_CASE_ERROR = "WRONG_CASE_ERROR";
const WRONG_LETTER_ERROR = "WRONG_LETTER_ERROR";
const MULTIPLICATION_SIGN_ERROR = "MULTIPLICATION_SIGN_ERROR";
const INVALID_SELECTION_ERROR = "INVALID_SELECTION_ERROR";
const CHOOSE_CORRECT_NUM_ERROR = "CHOOSE_CORRECT_NUM_ERROR";
const NOT_NONE_ABOVE_ERROR = "NOT_NONE_ABOVE_ERROR";

const ErrorCodes = {
    MISSING_PERCENT_ERROR,
    NEEDS_TO_BE_SIMPLIFIED_ERROR,
    APPROXIMATED_PI_ERROR,
    EXTRA_SYMBOLS_ERROR,
    WRONG_CASE_ERROR,
    WRONG_LETTER_ERROR,
    MULTIPLICATION_SIGN_ERROR,
    INVALID_SELECTION_ERROR,
    CHOOSE_CORRECT_NUM_ERROR,
    NOT_NONE_ABOVE_ERROR,
};

export default ErrorCodes;
