const MISSING_PERCENT_ERROR = "MISSING_PERCENT_ERROR";
const NEEDS_TO_BE_SIMPLIFIED_ERROR = "NEEDS_TO_BE_SIMPLIFIED_ERROR";
const APPROXIMATED_PI_ERROR = "APPROXIMATED_PI_ERROR";
const EXTRA_SYMBOLS_ERROR = "EXTRA_SYMBOLS_ERROR";
const WRONG_CASE_ERROR = "WRONG_CASE_ERROR";
const WRONG_LETTER_ERROR = "WRONG_LETTER_ERROR";
const MULTIPLICATION_SIGN_ERROR = "MULTIPLICATION_SIGN_ERROR";

const ErrorCodes = {
    MISSING_PERCENT_ERROR,
    NEEDS_TO_BE_SIMPLIFIED_ERROR,
    APPROXIMATED_PI_ERROR,
    EXTRA_SYMBOLS_ERROR,
    WRONG_CASE_ERROR,
    WRONG_LETTER_ERROR,
    MULTIPLICATION_SIGN_ERROR,
};

export default ErrorCodes;
