/* TODO(csilvers): fix these lint errors (http://eslint.org/docs/rules): */
/* eslint-disable no-var */
/* To fix, remove an entry above, run ka-lint, and fix errors. */

var _ = require("underscore");

var Widgets = require("./widgets.js");

// As new widgets get added here, please also make sure they get added in
// webapp perseus/traversal.py so they can be properly translated.
_.each([
    [require("./widgets/categorizer.jsx"),
     require("./widgets/categorizer-editor.jsx")],
    [require("./widgets/cs-program.jsx"),
     require("./widgets/cs-program-editor.jsx")],
    [require("./widgets/dropdown.jsx"),
     require("./widgets/dropdown-editor.jsx")],
    [require("./widgets/example-graphie-widget.jsx"),
     require("./widgets/example-graphie-widget-editor.jsx")],
    [require("./widgets/example-widget.jsx"),
     require("./widgets/example-widget-editor.jsx")],
    [require("./widgets/explanation.jsx"),
     require("./widgets/explanation-editor.jsx")],
    [require("./widgets/expression.jsx"),
     require("./widgets/expression-editor.jsx")],
    [require("./widgets/grapher.jsx"),
     require("./widgets/grapher-editor.jsx")],
    [require("./widgets/graded-group.jsx"),
     require("./widgets/graded-group-editor.jsx")],
    [require("./widgets/group.jsx"),
     require("./widgets/group-editor.jsx")],
    [require("./widgets/iframe.jsx"),
     require("./widgets/iframe-editor.jsx")],
    [require("./widgets/image.jsx"),
     require("./widgets/image-editor.jsx")],
    [require("./widgets/input-number.jsx"),
     require("./widgets/input-number-editor.jsx")],
    [require("./widgets/interaction.jsx"),
     require("./widgets/interaction-editor.jsx")],
    [require("./widgets/interactive-graph.jsx"),
     require("./widgets/interactive-graph-editor.jsx")],
    [require("./widgets/lights-puzzle.jsx"),
     require("./widgets/lights-puzzle-editor.jsx")],
    [require("./widgets/matrix.jsx"),
     require("./widgets/matrix-editor.jsx")],
    [require("./widgets/matcher.jsx"),
     require("./widgets/matcher-editor.jsx")],
    [require("./widgets/measurer.jsx"),
     require("./widgets/measurer-editor.jsx")],
    [require("./widgets/molecule.jsx"),
     require("./widgets/molecule-editor.jsx")],
    [require("./widgets/number-line.jsx"),
     require("./widgets/number-line-editor.jsx")],
    [require("./widgets/numeric-input.jsx"),
     require("./widgets/numeric-input-editor.jsx")],
    [require("./widgets/orderer.jsx"),
     require("./widgets/orderer-editor.jsx")],
    [require("./widgets/passage.jsx"),
     require("./widgets/passage-editor.jsx")],
    [require("./widgets/passage-ref.jsx"),
     require("./widgets/passage-ref-editor.jsx")],
    [require("./widgets/passage-ref-target.jsx"),
     require("./widgets/passage-ref-target-editor.jsx")],
    [require("./widgets/plotter.jsx"),
     require("./widgets/plotter-editor.jsx")],
    [require("./widgets/radio.jsx"),
     require("./widgets/radio/editor.jsx")],
    [require("./widgets/reaction-diagram.jsx"),
     require("./widgets/reaction-diagram-editor.jsx")],
    [require("./widgets/sequence.jsx"),
     require("./widgets/sequence-editor.jsx")],
    [require("./widgets/simple-markdown-tester.jsx"),
     require("./widgets/simple-markdown-tester-editor.jsx")],
    [require("./widgets/simulator.jsx"),
     require("./widgets/simulator-editor.jsx")],
    [require("./widgets/sorter.jsx"),
     require("./widgets/sorter-editor.jsx")],
    [require("./widgets/table.jsx"),
     require("./widgets/table-editor.jsx")],
    [require("./widgets/transformer.jsx"),
     require("./widgets/transformer-editor.jsx")],
    [require("./widgets/unit.jsx"),
     require("./widgets/unit-editor.jsx")],
    [require("./widgets/video.jsx"),
     require("./widgets/video-editor.jsx")],
], function(data) {
    Widgets.register(data[0].name, /* widget */ data[0], /* editor */ data[1]);
});

Widgets.validateAlignments();
