name: "Shared Node Cache"
description: "Install & cache our npm dependencies"

# The inputs this action expects.
inputs:
    node-version:
        description: "Node version to use"
        required: true

# The steps this action runs.
runs:
    using: "composite"
    steps:
        # NOTE: The pnpm/action-setup must come before action/setup-node!
        - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
          name: Install pnpm
          with:
              run_install: false

        - name: Use Node.js ${{ inputs.node-version }}
          uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
          with:
              node-version: ${{ inputs.node-version }}
              cache: pnpm

        - name: pnpm install
          shell: sh
          run: pnpm install ---frozen-lockfile
