name: 'Shared Node Cache'
description: 'Install & cache our npm dependencies'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: '16.x'
runs:
  using: "composite"
  steps:

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules and cypress binary
      uses: actions/cache@v2
      id: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-${{ inputs.node-version }}-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-v1-

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
