name: "Shared Node Cache"
description: "Install & cache our npm dependencies"

# The inputs this action expects.
inputs:
    node-version:
        description: "Node version to use"
        required: true
    ssh-private-key:
        description: "A private SSH key so that we can obtain private dependencies like our event schema package"
        required: true

# The steps this action runs.
# The order of the two steps below needs to be maintained.
# The ssh-agent step needs to be before the Node.js/Install step because our package.json uses
# git+ssh. As this requires a valid SSH key, the ssh-agent action must be before the yarn install.
runs:
    using: "composite"
    steps:
        - uses: webfactory/ssh-agent@v0.9.0
          with:
              ssh-private-key: ${{ inputs.ssh-private-key }}

        - name: Use Node.js ${{ inputs.node-version }} & Install & cache node_modules
          uses: Khan/actions@shared-node-cache-v2
          with:
              node-version: ${{ inputs.node-version }}

        - name: Check node_modules file hash
          shell: bash
          run: yarn hash-files 'node_modules/**/*'
