name: "Shared Node Cache"
description: "Install & cache our npm dependencies"

# The inputs this action expects.
inputs:
    node-version:
        description: "Node version to use"
        required: true
    ssh-private-key:
        description: "A private SSH key so that we can obtain private dependencies like our event schema package"
        required: true

# The steps this action runs.
runs:
    using: "composite"
    steps:
        - name: Use Node.js ${{ inputs.node-version }} & Install & cache node_modules
          uses: Khan/actions@shared-node-cache-v0
          with:
              node-version: ${{ inputs.node-version }}

        - uses: webfactory/ssh-agent@v0.7.0
          with:
              ssh-private-key: ${{ inputs.ssh-private-key }}
