name: "Shared Node Cache"
description: "Install & cache our npm dependencies"

# The inputs this action expects.
inputs:
    node-version:
        description: "Node version to use"
        required: true

# The steps this action runs.
# The order of the two steps below needs to be maintained.
runs:
    using: "composite"
    steps:
        - name: Set up node
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: yarn

        - name: yarn install
          run: yarn install
