name: Publish Storybook to Chromatic

# See: https://www.chromatic.com/docs/setup-turbosnap/#github-pull_request-triggers
on:
    workflow_dispatch:
        # Other Khan Academy repositories use this trigger for the chromaui/action
        # and it appears to work-ish, so we'll use the same. If it starts to break,
        # review the above URL to see how to fix it.
    pull_request:
    push:
        branches: [main]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    chromatic:
        name: Publish Storybook to Chromatic
        runs-on: ${{ vars.USE_GITHUB_RUNNERS == 'true' && '${{ matrix.os }}' || 'ephemeral-runner' }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [24.x]
        steps:
            # chromaui/@action doesn't work with shallow checkouts which is the
            # default for actions/checkout so we need to force it to checkout
            # more stuff.
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0

            - name: Secure Network
              uses: Khan/actions@secure-network-v1
              timeout-minutes: 5
              with:
                  conf-files: .github/npm-extra-domains.conf
                  # *.chromatic.com: Chromatic service for uploading and comparing Storybook snapshots
                  # chromatic-builds.s3.us-west-2.amazonaws.com: S3 bucket for Storybook file uploads (presigned URLs returned by index.chromatic.com GraphQL API)
                  extra-domains: index.chromatic.com notify.dev-chromatic.com notify.staging-chromatic.com notify.chromatic.com chromatic.com chromatic-builds.s3.us-west-2.amazonaws.com

            - name: Install & cache node_modules
              uses: ./.github/actions/shared-node-cache
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Publish to Chromatic for visual testing
              uses: chromaui/action@f191a0224b10e1a38b2091cefb7b7a2337009116 # v16.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  buildScriptName: "build:storybook"
                  autoAcceptChanges: "main"
                  onlyStoryFiles: "**/*-regression.stories.tsx"
                  # NOTE: We cannot enable `onlyChanged` because it is
                  # incompatible with `onlyStoryFiles` which we use above.
                  # onlyChanged: true # Enable TurboSnap!
