name: Publish Storybook to Chromatic

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    chromatic:
        name: Publish Storybook to Chromatic
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.x]
        steps:
            # chromaui/@action doesn't work with shallow checkouts which is the
            # default for actions/checkout so we need to force it to checkout
            # more stuff.
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install & cache node_modules
              uses: ./.github/actions/shared-node-cache
              with:
                  node-version: ${{ matrix.node-version }}
                  ssh-private-key: ${{ secrets.KHAN_ACTIONS_BOT_SSH_PRIVATE_KEY }}

            - name: Publish to Chromatic
              uses: chromaui/action@latest
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  autoAcceptChanges: "main"
                  # Generate snapshots for only changed stories
                  # See: https://www.chromatic.com/docs/turbosnap
                  onlyChanged: true
